### ISSUE TITLE
Clarify licences, pls

### ISSUE THREAD

**Issue by BasilYes** [Lakshman-YT/Mnstr-Trck-GDT-4-series#1]
> You can use the provided scripts for your own projects, but please note that the car model used in this series is not owned by us. You may encounter issues if you use these models for commercial purposes.

Just add license file to this repo (MIT or apache 2 if you want attribution or cc0 if don't is most common and simple licenses for "free to use anywhere" projects) and link to car model (or just license of car model) inside readme.
It's very important because without this none can't use this code legally.
(P.S. Godot under MIT license and it's most common license in godot community)

**Comment by Lakshman-YT** [comment]
> > You can use the provided scripts for your own projects, but please note that the car model used in this series is not owned by us. You may encounter issues if you use these models for commercial purposes.
> 
> Just add license file to this repo (MIT or apache 2 if you want attribution or cc0 if don't is most common and simple licenses for "free to use anywhere" projects) and link to car model (or just license of car model) inside readme. It's very important because without this none can't use this code legally. (P.S. Godot under MIT license and it's most common license in godot community)

**Comment by Lakshman-YT** [comment]
> > You can use the provided scripts for your own projects, but please note that the car model used in this series is not owned by us. You may encounter issues if you use these models for commercial purposes.
> 
> Just add license file to this repo (MIT or apache 2 if you want attribution or cc0 if don't is most common and simple licenses for "free to use anywhere" projects) and link to car model (or just license of car model) inside readme. It's very important because without this none can't use this code legally. (P.S. Godot under MIT license and it's most common license in godot community)

1. I will add an MIT license to this repository.
2. I've made extensive efforts to find the original link to the car model before uploading it to GitHub, but unfortunately, it seems that the user may have removed the model from Sketchfab, or there is another issue preventing access to the exact license and link. Given this situation, it's best to inform users to avoid using the car model, especially for commercial purposes.

**Comment by BasilYes** [comment]
Thanks!
